apiVersion: v1
data:
    cf-api-key: ENC[AES256_GCM,data:eIsfEiPKKGVmSf4+TK9XfpdkVKiuQbhLEhJX4WWCVIoKnszrfZ39DV/8SR/9BR0SZE8dAduP+wPAYGkTm5K9S73KUV8S1OIgyIJVhyuGV2M=,iv:rlHfyxMbJisYs5h7h9yvMFqvPBo5txIbUNs4XNJvlmo=,tag:sKXlayKUafP2LqoLtzV5zQ==,type:str]
kind: Secret
metadata:
    name: cf-api-token
    namespace: b02-paper-minecraft
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T20:41:56Z"
    mac: ENC[AES256_GCM,data:X7cTkEf/3UE+/UtZwqaOQxMTKmYlCA9rsTBgpV2ZaIxwN2rghRWfaXET/SLADSsPdAaznZcfL0m/34saSHX6kSrxkCc9QtlzU93PbfNjGIm4CTpl3EmourIm2iptgG+g7MwHGf8PC9QZbLT5PTDtK3UZF1AvtjgXqTNLirmie1g=,iv:skf71ZP/TDXvxPLCa9OBHGmEaiEStJUheIIe42JN/BI=,tag:He9Q86Em8DN0eyWpu3YPgA==,type:str]
    pgp:
        - created_at: "2025-01-31T20:41:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwFcjQZ1ckKcAQ/9GUrhBCCnH1yrDi4/Y/6ahCF59W+1SqATpwQ6FupTr0zP
            BAzL8W9FigWFRGI5xkj/4QMqeK9aoVJuowfGCmarhjVFl9KfAFn60QomLvW3MxiW
            oC/O5Oo7WbUZpOfRVPjJuDpkr48jmtn1aaliVLEyKuYZV/0el7hRQDvjQ/ff/+uG
            kCUEWFWfqaJjBS/t9gkeBhmVXF3wU4deJhnoPqNP6bbM8oAOKy5HTYckDzwaLB3Y
            8yo5B9kJpDNMBTHwQV8BgobU9J9ZSHEYmfOwpQc+A4/FzzmyLAIPFcqaJLQIPIqa
            zHO30i/Ae8euZI1H0Dz6fSazr1cWDmZVt+tFDJ6ICanzWN0f218rxfzp1t/yUxgc
            RauiZR42J9GJIFNVD2pWnXHs/eqE9lPOvrIREfkCMEPIvvKk5eD5HzMhLQo1SvW3
            Jxkxe8QkOT/dlqnqiydtWrTaDm5AAk4dYOQmNFfkj3LoetftkERXn6Hvf48NmxqB
            zE0sJCpH54oT4Qu5fzGyofYDVBaysKZ8AY8hNH/DGNq6ETebRFz9PI3Y78gap5d2
            4Fa3bLSWb5AeezcIGEs8gRhatPdO8fPZiVvoLBFz6xKJ6NNdAstozSLPr2H52hii
            5UsTmVYWfCdnLc+0gjiVrozRE7vD634ZMFsTzpq1n+SEATIn8cYHcmSubBekzRnU
            aAEJAhAU6MiQYcL2UTmz+cAW5mL7GWXej1wAsB3I8QiZ3QiAwj5MO2O0+PXdnKQZ
            qohvI0U6VQ2ClK9d9z31Q/50IB8NlC/oyTQILxFYJqJF7vBEYsWA61z02Fcoi8XE
            9QHJAAKzU0yX
            =8BlX
            -----END PGP MESSAGE-----
          fp: 4C460A5D1A91A52F3E204754CA746D9D4345890B
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.9.4
