apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

# operators
  - operators/connectivity/
  - operators/monitoring/
  - operators/storage/

# projects
  - projects/gameservers/minecraft/
  - projects/nextcloud/
  - projects/web-rcon/
