apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minecraft-rcon-password.yaml



# # operators
#   - ../../secrets/home-mck/operators/connectivity/
#   - ../../secrets/home-mck/operators/monitoring/
#   - ../../secrets/home-mck/operators/storage/

# # projects
#   - ../../secrets/home-mck/projects/gameservers/minecraft/
#   - ../../secrets/home-mck/projects/nextcloud/
#   - ../../secrets/home-mck/projects/web-rcon/
