apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  - b01a/
  - b02/

  # Monitoring
  - alertmanager-config.yaml

  # Storage
  - csi-proxmox.yaml

  # Connectivity
  - teleport-kube-agent-join-token.yaml

  # Web-Rcon
  - rcon-config.yaml
  
  # Nextcloud
  - nextcloud-mariadb-auth.yaml
  - nextcloud-redis-auth.yaml

