apiVersion: v1
data:
    auth-token: ENC[AES256_GCM,data:i7rurw9J5IRrBn3lKdwCzA/HXBNKSsv4ZM1r4MTeT/vRlKqhSRwtN12DBEs=,iv:DaALJkjCzf+7ImFAkbCHtqB1ni+z7gMO/2hS56qsR3w=,tag:DsLHjee7xQodAmUpswJEcA==,type:str]
kind: Secret
metadata:
    name: teleport-kube-agent-join-token
    namespace: teleport-kube-agent
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T20:40:28Z"
    mac: ENC[AES256_GCM,data:zafU0qhXY0zzbPZWr85L5lLpebt/xG7Wl5Ogl3GmMKxaUAUKexw1Qwu35iOxONJ1v78K7zZSNGnxBwltDzyZUgJ54xkkj6UwIQJwjmnf8lP1yp8jSXsn2mh6s7D/Isqh7vvODhVUEyUABRY5zIeN0F6FMbgnop4Ij5o4K0yqRyI=,iv:HmyEOhwH7e7v0gPv2CytgROg+E68dY8AjVIAnk3xDV8=,tag:fbmTwcP4gNrEoIMKVM0zzQ==,type:str]
    pgp:
        - created_at: "2025-01-31T20:40:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwFcjQZ1ckKcARAAlowmaHWsNEkAviqJrQI1/tQKmsGmnztQ1vH3PeHalguu
            t+0jNQfrT1RhNyGdcL/NkGTxO8lCyqbPHv7S2yBqUnHuLtw5au2uvh8icV7xsv/k
            fyDfIxW/EAXcXI1ZWAaLsgLvp7Vkh2DxOhP0wSzYBOMTi6cNFmgTE06iLm5WA05P
            jlKByhBw+atUbdae+yvXBhEfUP/Kk42mRKRVV5H/esxhWHgHOM32yDZwTlTBD7El
            2Qos+zAf8lBJ4x6S1kMwXhsI/6Hr58QRRQd6VpfdiV5YbjEWspV2G6iakvOINVna
            21Pd1lGDWM4K+tpVieM/P7OiQvpPhMrhsasRMtBQrJy0tpWABx4erXXtITbGRKOM
            +hxJx0xKcNZ5QoRABaq7iL6ua0c0BLGVpk2MK5O+4COdXH3K4Bc00I4066jM7VK7
            UCsu73tzGRyboacqET5ZGfNEWWGmbDoc3UAXMJhFx6e7XNNDe6Z8cHxPdOUYxpxu
            Z1ScX4N1+XQxITOS30yjeU48Gk6ad7/byrxNmCmBbzQO0dUE6SOsKV+Pf790cVif
            zhXdUv1fhDD/y6gulitaX0beJjyl2QItfAP9jO1+XpikRItJ4DJGCrLelm3mZRW/
            Nyv3cqAmTZil5eSH4MSviiT8ayvSt1KB7pSfRqT7e5QPdhO6Xw0crnaOlNvyvELU
            aAEJAhCe4c9KDl31nvfpf/icFTIshMi+KC1OAW+lihMf0uCnFMof2kZZ1lNzoWcn
            A5OKr5qQf3N0VL50WBgXo+U8Ir+EyMgNvTyFeo/RqAFd06E10URQP9EM2kMC8Kft
            OjforEKs57vF
            =5Gj6
            -----END PGP MESSAGE-----
          fp: 4C460A5D1A91A52F3E204754CA746D9D4345890B
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.9.4
