apiVersion: v1
data:
    auth-token: ENC[AES256_GCM,data:2zpPRbJDv5fD2Jruzu+YnLknHLpqXb1P0u23OqxkUGDtursqWHKXmPkve1A=,iv:frSF+zfyx5EabYHDeds1EZOq4jwoJG7YCejlzY0zmX4=,tag:x8Ni58kF7W2Ts63CM1Pk2g==,type:str]
kind: Secret
metadata:
    name: teleport-kube-agent-join-token
    namespace: teleport-kube-agent
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T20:37:12Z"
    mac: ENC[AES256_GCM,data:2JkNNTfFydFyLpaY4rclJZSXv1NMhR+tHGTmBhSI5nifX2YcLUp5fEaITNl9BUEoC6oE2hpBWqpC5z+Wcry4GE2je37ZifdLOOS3e3PUaMquHyLMmv7tEUGGoiRXcLxTc41Lt33PVHQWVT2L1P+E95kuPkyDhKGavRN/P2if2fk=,iv:oSIjqmtQ05rsjn2tnwmu+khcfE5OEr6T5//IQKOc/mU=,tag:ZW/noYEnC1FO66ssXCgYmw==,type:str]
    pgp:
        - created_at: "2025-01-31T20:37:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwFcjQZ1ckKcARAA4vqZ9zkJza/UI2dCZNW82tT/yvxnHW5G2/qNFh4uZDpO
            DMtPyjLB49aOgh9PdCxtxbpHEuo51cJtFyajOXnpcO9RPwgXUA5RQNeqtctaeNYu
            /jKoqabpjEDDK07RDTn1lXw05WPscUEysiDJObmXLJnGIh3nahLFSg72PC/q56ij
            eyp2WT2E4lNuk6JaP/nTvscRyETYvQNdZdtZnwTCR+dgj++E16Fyy4NsEFT6NDja
            E+oXxkITZNvcbEfn0qhkm61V7XQg5inYyF8Fvatt2NnZ6mc1teDcxIghcj+gPg82
            jJWLdBoNTbmnc6UhsGwpLZcjMDi4wizTMdM3jubhCVby27DGUed16t0pH3jeuE/l
            Kk8vLO2i4TazX36uMJEQ+cU/jPTuchAyxfZW5i2Yz4rWmn+PTgFXJXRQLmA5e24F
            tMxPKTcauFeIv8vvXD7M7JP2dy5Ltbg8srWp70ESv3t62MBPhax0U6NvfDIBpfdu
            iHbAK1k5KVwPsBCnu7/InySYHNoX54OWVPfma2a4+GA8cwZzCTTb/B8E/YIgiuzh
            bw0T94xo+Z6r+tuhQW4E7PaB9fMQX28orCBB7F87JMsJjqv+diIGQjoBRgJO70AM
            zeJtk7WSEHScqRzqByxkFzeVO2P3UGROHHp0DeyU/8V48rLDaXf2EKIWJe6eJvHU
            aAEJAhA8SEF/QhYUgL+xgWZ3VdIzC3ucWUcssOGKJN6vt9mIgyI1zuejEdk0Zz4J
            AnD0N8UdPyLrmppxLzzwrxNWvjw1DcVrY1zPz+iu8P1T37ja79baeuRF1UayhGR9
            DzJQDdzcinM3
            =iMiq
            -----END PGP MESSAGE-----
          fp: 4C460A5D1A91A52F3E204754CA746D9D4345890B
    encrypted_regex: ^(data|stringData|secrets)$
    version: 3.9.4
